[project]
name = "pochmurnedni"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "just-playback>=0.1.8",
    "mido>=1.3.3",
    "pygame>=2.6.1",
]
